import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { headers } from "next/headers";
import ContextProvider from "@/context";
import Navbar from "@/components/Navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const headersObj = await headers();
  const cookies = headersObj.get("cookie");

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ContextProvider cookies={cookies}>
        <div className="flex flex-col min-h-screen relative">
          <Navbar />
          <main>
            {children}
          </main>
          <footer className="w-full text-center text-sm py-2 absolute bottom-0">
          <span className="text-purple-400 font-mono">
            <a href="https://x.com/gabriell_santi" target="_blank" rel="noopener noreferrer">
              Built by <strong>Santi</strong>
            </a>
          </span>
          </footer>
        </div>
        </ContextProvider>
      </body>
    </html>
  );
}
